/**
 * Optional Netlify / CI step: merge GitHub coordinates into js/cms-config.js.
 *
 * Environment variables:
 *   CEC_GITHUB_REPO    — owner/repo (e.g. acme-corp/cec-contractors)
 *   CEC_GITHUB_BRANCH  — optional, default main
 *
 * Netlify: Site settings → Environment variables → add CEC_GITHUB_REPO for Production.
 * Build command example: node scripts/build-config.js
 */

const fs = require("fs");
const path = require("path");

const repoEnv = process.env.CEC_GITHUB_REPO || "";
const branch = process.env.CEC_GITHUB_BRANCH || "main";

function parseRepo(str) {
  var parts = String(str || "")
    .trim()
    .split("/")
    .filter(Boolean);
  if (parts.length < 2) return null;
  return { owner: parts[0], repo: parts.slice(1).join("/") };
}

var parsed = parseRepo(repoEnv);
var outPath = path.join(__dirname, "..", "js", "cms-config.js");

var body;
if (!parsed) {
  body =
    "/** Optional: set CEC_GITHUB_REPO during build to inject GitHub coordinates here. */\n" +
    "window.CEC_CMS_CONFIG = window.CEC_CMS_CONFIG || {};\n";
  console.warn(
    "[build-config] CEC_GITHUB_REPO missing — wrote default cms-config.js (HTML meta tags still work)."
  );
} else {
  var patch = { github: { owner: parsed.owner, repo: parsed.repo, branch: branch } };
  body =
    "/* Generated by scripts/build-config.js */\n" +
    "window.CEC_CMS_CONFIG = Object.assign(window.CEC_CMS_CONFIG || {}, " +
    JSON.stringify(patch, null, 2) +
    ");\n";
  console.log("[build-config] Wrote js/cms-config.js for repo " + repoEnv);
}

fs.writeFileSync(outPath, body, "utf8");
